jenkins:
  systemMessage: "Azure Infrastructure Lab Jenkins"

  numExecutors: 2

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false


unclassified:

  location:
    url: http://localhost:8080/

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: github-token
              description: GitHub Personal Access Token
              username: ${GITHUB_USERNAME}
              password: ${GITHUB_TOKEN}
              scope: GLOBAL

          - azure:
              id: azure-service-principal
              description: Azure Service Principal for Terraform Lab
              clientId: ${AZURE_CLIENT_ID}
              clientSecret: ${AZURE_CLIENT_SECRET}
              tenant: ${AZURE_TENANT_ID}
              subscriptionId: ${AZURE_SUBSCRIPTION_ID}
              scope: GLOBAL
