jenkins:
  systemMessage: "Azure Infrastructure Lab Jenkins"

  numExecutors: 2

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false


unclassified:

  location:
    url: http://localhost:8080/

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: github-token
              description: GitHub Personal Access Token
              username: ${GITHUB_USERNAME}
              password: ${GITHUB_TOKEN}
              scope: GLOBAL
